<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<title>Identify yourself</title>
	<link rel="stylesheet" type="text/css" href="css/view.css"/>
	<link href="" rel="stylesheet">
	<script type="text/javascript" src="view.js"></script>

</head>
<body id="main_body" >
	
	<img id="top" src="top.png" alt="">
	<div id="form_container">
		<h1><a>Identify Yourself</a></h1>
		<form id="form_56143" class="appnitro"  method="GET" action="Data">
			<div class="form_description">
			<h2>Fill this form</h2>
			<p>This is your form description. Click here to edit.</p>
		</div>						
		<ul >
			<li id="li_1" >
		<label class="description" for="element_1">Name </label>
		<span>
			<input id="element_1_1" name= "spyName" class="element text" maxlength="255" size="8"/>
		</span>
		</li>		<li id="li_3" >
		<label class="description" for="element_3">Specialist </label>
		<span>
			<input id="element_3_1" name="assassin" class="element checkbox" type="checkbox" value="1" />
			<label class="choice" for="element_3_1">Assassin</label>
			<input id="element_3_2" name="whistle" class="element checkbox" type="checkbox" value="1" />
			<label class="choice" for="element_3_2">Whistle Blower</label>
			<input id="element_3_3" name="eaves" class="element checkbox" type="checkbox" value="1" />
			<label class="choice" for="element_3_3">Eavesdroper</label>

		</span> 
		</li>
			
					<li class="buttons">
			    <input type="hidden" name="form_id" value="56143" />
				<input id="saveForm" class="button_text" type="submit" name="submit" value="Submit" action="spyForm"/>
		</li>
			</ul>
		</form>	
		<div id="footer">
			Generated by <a href="http://www.phpform.org">pForm</a>
		</div>
	</div>
	<img id="bottom" src="bottom.png" alt="">
	</body>
</html>